// Enhanced Reel System Types

export type ReelType =
    | 'skill-tutorial'
    | 'pvp-highlight'
    | 'project-showcase'
    | 'ai-learning'
    | 'collaboration'
    | 'achievement';

export type DifficultyLevel = 'beginner' | 'intermediate' | 'advanced' | 'expert';
export type CompensationType = 'paid' | 'equity' | 'open-source' | 'learning';
export type AchievementType = 'level-up' | 'tournament-win' | 'certification' | 'milestone';
export type AchievementRarity = 'common' | 'rare' | 'epic' | 'legendary';

// User type
export interface ReelUser {
    id: string;
    username: string;
    name: string;
    avatarUrl?: string;
    isVerified: boolean;
    isFollowed: boolean;
    skills?: string[];
}

// Tutorial-specific metadata
export interface TutorialMetadata {
    difficultyLevel: DifficultyLevel;
    learningObjective: string;
    estimatedLearningTime: number; // in seconds
    seriesId?: string;
    seriesIndex?: number;
    seriesTotal?: number;
}

// PvP-specific metadata
export interface PvPMetadata {
    battleId: string;
    participants: ReelUser[];
    winner: ReelUser;
    challengeType: string;
    finalScore: { [userId: string]: number };
    autoGenerated: boolean;
    duration: number; // battle duration in seconds
}

// Project showcase metadata
export interface ProjectMetadata {
    projectId: string;
    projectName: string;
    techStack: string[];
    liveUrl?: string;
    githubUrl?: string;
    lookingForCollaborators: boolean;
    teamSize?: number;
}

// AI Learning metadata
export interface AILearningMetadata {
    targetSkill: string;
    recommendationReason: string;
    actionableSteps: string[];
    priority: 'low' | 'medium' | 'high';
}

// Collaboration metadata
export interface CollaborationMetadata {
    projectName: string;
    rolesNeeded: string[];
    requiredSkills: string[];
    timeCommitment: string;
    compensation: CompensationType;
    applicationsCount: number;
    deadline?: Date;
    isActive: boolean;
}

// Achievement metadata
export interface AchievementMetadata {
    achievementType: AchievementType;
    achievementName: string;
    earnedAt: Date;
    rarity: AchievementRarity;
    relatedSkill?: string;
    xpEarned?: number;
}

// Main Reel interface
export interface Reel {
    id: string;
    type: ReelType;

    // Video content
    videoUrl: string;
    thumbnailUrl?: string;
    duration: number; // in seconds

    // Creator
    creator: ReelUser;
    createdAt: Date;

    // Content
    caption: string;
    skillTags: string[];

    // Engagement
    likes: number;
    comments: number;
    shares: number;
    saves: number;
    views: number;
    isLiked: boolean;

    // AI Recommendation
    recommendationReason?: string;
    recommendationScore?: number; // 0-100

    // Type-specific metadata (only one should be populated based on type)
    tutorial?: TutorialMetadata;
    pvp?: PvPMetadata;
    project?: ProjectMetadata;
    aiLearning?: AILearningMetadata;
    collaboration?: CollaborationMetadata;
    achievement?: AchievementMetadata;
}

// Feed mode type
export type FeedMode = 'all' | 'learning' | 'career' | 'pvp' | 'discover';

// Engagement signal for recommendation engine
export interface EngagementSignal {
    reelId: string;
    watchTime: number;
    scrollSpeed: number;
    completionRate: number;
    interactionType?: 'like' | 'comment' | 'share' | 'save' | 'skip' | 'challenge' | 'apply';
}

// Helper type guards
export function isTutorialReel(reel: Reel): reel is Reel & { tutorial: TutorialMetadata } {
    return reel.type === 'skill-tutorial' && !!reel.tutorial;
}

export function isPvPReel(reel: Reel): reel is Reel & { pvp: PvPMetadata } {
    return reel.type === 'pvp-highlight' && !!reel.pvp;
}

export function isProjectReel(reel: Reel): reel is Reel & { project: ProjectMetadata } {
    return reel.type === 'project-showcase' && !!reel.project;
}

export function isAILearningReel(reel: Reel): reel is Reel & { aiLearning: AILearningMetadata } {
    return reel.type === 'ai-learning' && !!reel.aiLearning;
}

export function isCollabReel(reel: Reel): reel is Reel & { collaboration: CollaborationMetadata } {
    return reel.type === 'collaboration' && !!reel.collaboration;
}

export function isAchievementReel(reel: Reel): reel is Reel & { achievement: AchievementMetadata } {
    return reel.type === 'achievement' && !!reel.achievement;
}
