"""Initial schema

Revision ID: 89fecc1dc91c
Revises: 
Create Date: 2026-05-02 00:15:52.650688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89fecc1dc91c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=True),
    sa.Column('rarity', sa.String(), nullable=True),
    sa.Column('requirement_type', sa.String(), nullable=True),
    sa.Column('requirement_value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_achievements_id'), 'achievements', ['id'], unique=False)
    op.create_table('battle_pass_seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battle_pass_seasons_id'), 'battle_pass_seasons', ['id'], unique=False)
    op.create_table('daily_quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('quest_type', sa.String(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=True),
    sa.Column('difficulty_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_quests_id'), 'daily_quests', ['id'], unique=False)
    op.create_table('platform_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('total_users', sa.Integer(), nullable=True),
    sa.Column('active_users_24h', sa.Integer(), nullable=True),
    sa.Column('active_users_7d', sa.Integer(), nullable=True),
    sa.Column('new_users_24h', sa.Integer(), nullable=True),
    sa.Column('total_posts', sa.Integer(), nullable=True),
    sa.Column('new_posts_24h', sa.Integer(), nullable=True),
    sa.Column('total_pvp_matches', sa.Integer(), nullable=True),
    sa.Column('matches_played_24h', sa.Integer(), nullable=True),
    sa.Column('total_skills', sa.Integer(), nullable=True),
    sa.Column('verified_skills', sa.Integer(), nullable=True),
    sa.Column('platform_revenue', sa.Float(), nullable=True),
    sa.Column('avg_session_duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_metrics_date'), 'platform_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_platform_metrics_id'), 'platform_metrics', ['id'], unique=False)
    op.create_table('pvp_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=True),
    sa.Column('initial_code', sa.Text(), nullable=True),
    sa.Column('test_cases', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pvp_challenges_id'), 'pvp_challenges', ['id'], unique=False)
    op.create_table('skill_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_index(op.f('ix_skill_categories_id'), 'skill_categories', ['id'], unique=False)
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('prize_pool', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournaments_id'), 'tournaments', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('banner_url', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('xp_points', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('ranking_score', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('online_status', sa.String(), nullable=True),
    sa.Column('account_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('ai_profile_insights',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('growth_suggestions', sa.Text(), nullable=True),
    sa.Column('career_prediction', sa.Text(), nullable=True),
    sa.Column('collab_recommendations', sa.Text(), nullable=True),
    sa.Column('skill_gap_analysis', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('battle_pass_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('tier_number', sa.Integer(), nullable=False),
    sa.Column('xp_required', sa.Integer(), nullable=False),
    sa.Column('reward_data', sa.JSON(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['battle_pass_seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battle_pass_tiers_id'), 'battle_pass_tiers', ['id'], unique=False)
    op.create_table('chat_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=False),
    sa.Column('user2_id', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_rooms_id'), 'chat_rooms', ['id'], unique=False)
    op.create_table('communities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('banner_url', sa.String(), nullable=True),
    sa.Column('theme_color', sa.String(), nullable=True),
    sa.Column('privacy', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communities_id'), 'communities', ['id'], unique=False)
    op.create_index(op.f('ix_communities_name'), 'communities', ['name'], unique=True)
    op.create_index(op.f('ix_communities_slug'), 'communities', ['slug'], unique=True)
    op.create_table('connection_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connection_requests_id'), 'connection_requests', ['id'], unique=False)
    op.create_index(op.f('ix_connection_requests_receiver_id'), 'connection_requests', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_connection_requests_sender_id'), 'connection_requests', ['sender_id'], unique=False)
    op.create_table('creator_metrics',
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('content_quality_score', sa.Float(), nullable=True),
    sa.Column('authority_level', sa.Integer(), nullable=True),
    sa.Column('monetization_earnings', sa.Float(), nullable=True),
    sa.Column('viral_velocity', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('creator_id')
    )
    op.create_table('creator_monetization',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_earnings', sa.Float(), nullable=True),
    sa.Column('pending_payout', sa.Float(), nullable=True),
    sa.Column('active_subscriptions', sa.Integer(), nullable=True),
    sa.Column('tips_received', sa.Float(), nullable=True),
    sa.Column('stripe_account_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('external_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('platform_username', sa.String(), nullable=False),
    sa.Column('profile_url', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('imported_stats', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_accounts_id'), 'external_accounts', ['id'], unique=False)
    op.create_table('feed_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('feed_snapshot', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_cache_id'), 'feed_cache', ['id'], unique=False)
    op.create_table('followers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('following_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_followers_id'), 'followers', ['id'], unique=False)
    op.create_table('leaderboard',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_type', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('rank_position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'skill_type')
    )
    op.create_table('match_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('skill_type', sa.String(), nullable=True),
    sa.Column('queue_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_match_queue_id'), 'match_queue', ['id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('player1_id', sa.Integer(), nullable=True),
    sa.Column('player2_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_id', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('post_type', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('media_url', sa.String(), nullable=True),
    sa.Column('skill_tags', sa.JSON(), nullable=True),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_table('profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('banner_url', sa.Text(), nullable=True),
    sa.Column('learning_goals', sa.Text(), nullable=True),
    sa.Column('collaboration_preference', sa.String(), nullable=True),
    sa.Column('privacy_setting', sa.String(), nullable=True),
    sa.Column('experience_level', sa.String(), nullable=True),
    sa.Column('portfolio_links', sa.JSON(), nullable=True),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('experience_data', sa.JSON(), nullable=True),
    sa.Column('education_data', sa.JSON(), nullable=True),
    sa.Column('projects_data', sa.JSON(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('resume_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('reels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=False),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('skill_tags', sa.JSON(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reels_id'), 'reels', ['id'], unique=False)
    op.create_table('rivalries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rival_user_id', sa.Integer(), nullable=True),
    sa.Column('win_streak', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rival_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rivalries_id'), 'rivalries', ['id'], unique=False)
    op.create_table('skill_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('skill_name', sa.String(), nullable=False),
    sa.Column('verification_level', sa.String(), nullable=True),
    sa.Column('verification_method', sa.String(), nullable=True),
    sa.Column('verification_score', sa.Float(), nullable=True),
    sa.Column('token_id', sa.String(), nullable=True),
    sa.Column('transaction_hash', sa.String(), nullable=True),
    sa.Column('wallet_address', sa.String(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('date_awarded', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_badges_id'), 'skill_badges', ['id'], unique=False)
    op.create_table('skill_endorsements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endorser_user_id', sa.Integer(), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('skill_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['endorser_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_endorsements_endorser_user_id'), 'skill_endorsements', ['endorser_user_id'], unique=False)
    op.create_index(op.f('ix_skill_endorsements_id'), 'skill_endorsements', ['id'], unique=False)
    op.create_index(op.f('ix_skill_endorsements_skill_name'), 'skill_endorsements', ['skill_name'], unique=False)
    op.create_index(op.f('ix_skill_endorsements_target_user_id'), 'skill_endorsements', ['target_user_id'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['skill_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_canonical_name'), 'skills', ['canonical_name'], unique=True)
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_table('social_graph_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('connected_user_id', sa.Integer(), nullable=True),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('weight_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['connected_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_graph_edges_id'), 'social_graph_edges', ['id'], unique=False)
    op.create_table('tournament_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('match_number', sa.Integer(), nullable=True),
    sa.Column('player1_id', sa.Integer(), nullable=True),
    sa.Column('player2_id', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('player1_score', sa.Integer(), nullable=True),
    sa.Column('player2_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournament_matches_id'), 'tournament_matches', ['id'], unique=False)
    op.create_table('tournament_participants',
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('seed_number', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('matches_played', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('tournament_id', 'user_id')
    )
    op.create_table('tournament_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=True),
    sa.Column('badge_name', sa.String(), nullable=True),
    sa.Column('badge_icon', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournament_rewards_id'), 'tournament_rewards', ['id'], unique=False)
    op.create_table('user_account_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('theme_mode', sa.String(), nullable=True),
    sa.Column('content_filter_level', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('achievement_id', sa.Integer(), nullable=True),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_achievements_id'), 'user_achievements', ['id'], unique=False)
    op.create_table('user_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activities_id'), 'user_activities', ['id'], unique=False)
    op.create_table('user_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=False),
    sa.Column('user2_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_connections_id'), 'user_connections', ['id'], unique=False)
    op.create_index(op.f('ix_user_connections_user1_id'), 'user_connections', ['user1_id'], unique=False)
    op.create_index(op.f('ix_user_connections_user2_id'), 'user_connections', ['user2_id'], unique=False)
    op.create_table('user_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('target', sa.Float(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('reward', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_goals_id'), 'user_goals', ['id'], unique=False)
    op.create_index(op.f('ix_user_goals_user_id'), 'user_goals', ['user_id'], unique=False)
    op.create_table('user_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('interest_tag', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_interests_id'), 'user_interests', ['id'], unique=False)
    op.create_table('user_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('media_url', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_media_id'), 'user_media', ['id'], unique=False)
    op.create_table('user_notification_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('battle_notifications', sa.Boolean(), nullable=True),
    sa.Column('message_notifications', sa.Boolean(), nullable=True),
    sa.Column('community_notifications', sa.Boolean(), nullable=True),
    sa.Column('marketing_notifications', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_presence',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_presence_is_online'), 'user_presence', ['is_online'], unique=False)
    op.create_table('user_privacy_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_visibility', sa.String(), nullable=True),
    sa.Column('allow_messages', sa.String(), nullable=True),
    sa.Column('allow_tagging', sa.Boolean(), nullable=True),
    sa.Column('show_activity_status', sa.Boolean(), nullable=True),
    sa.Column('show_battle_history', sa.Boolean(), nullable=True),
    sa.Column('show_skill_levels', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('project_description', sa.Text(), nullable=True),
    sa.Column('project_link', sa.String(), nullable=True),
    sa.Column('project_image', sa.String(), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_projects_id'), 'user_projects', ['id'], unique=False)
    op.create_index(op.f('ix_user_projects_user_id'), 'user_projects', ['user_id'], unique=False)
    op.create_table('user_quest_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quest_id', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['quest_id'], ['daily_quests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_quest_status_id'), 'user_quest_status', ['id'], unique=False)
    op.create_table('user_rank',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_skill_xp', sa.Integer(), nullable=True),
    sa.Column('rank', sa.String(), nullable=True),
    sa.Column('rank_points', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_reputation',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reputation_score', sa.Integer(), nullable=True),
    sa.Column('trust_level', sa.String(), nullable=True),
    sa.Column('skill_authority_score', sa.Float(), nullable=True),
    sa.Column('social_trust_score', sa.Float(), nullable=True),
    sa.Column('professional_credibility_score', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_resumes_id'), 'user_resumes', ['id'], unique=False)
    op.create_index(op.f('ix_user_resumes_user_id'), 'user_resumes', ['user_id'], unique=False)
    op.create_table('user_security_score',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('toxicity_score', sa.Float(), nullable=True),
    sa.Column('spam_probability', sa.Float(), nullable=True),
    sa.Column('bot_probability', sa.Float(), nullable=True),
    sa.Column('penalty_score', sa.Integer(), nullable=True),
    sa.Column('is_shadowbanned', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_social_stats',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('posts_count', sa.Integer(), nullable=True),
    sa.Column('reels_count', sa.Integer(), nullable=True),
    sa.Column('battle_wins', sa.Integer(), nullable=True),
    sa.Column('battle_losses', sa.Integer(), nullable=True),
    sa.Column('xp_total', sa.Integer(), nullable=True),
    sa.Column('rank_level', sa.String(), nullable=True),
    sa.Column('streak_days', sa.Integer(), nullable=True),
    sa.Column('streak_last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('battle_pass_tier', sa.Integer(), nullable=True),
    sa.Column('xp_multiplier', sa.Float(), nullable=True),
    sa.Column('reputation_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('community_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_members_id'), 'community_members', ['id'], unique=False)
    op.create_table('community_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('media_urls', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_posts_id'), 'community_posts', ['id'], unique=False)
    op.create_table('match_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_submissions_id'), 'match_submissions', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(), nullable=True),
    sa.Column('media_url', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_is_read'), 'messages', ['is_read'], unique=False)
    op.create_index(op.f('ix_messages_room_id'), 'messages', ['room_id'], unique=False)
    op.create_table('post_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('media_url', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_media_id'), 'post_media', ['id'], unique=False)
    op.create_index(op.f('ix_post_media_post_id'), 'post_media', ['post_id'], unique=False)
    op.create_table('pvp_matches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('player1_id', sa.Integer(), nullable=True),
    sa.Column('player2_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('battle_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('match_status', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('spectator_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['player1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pvp_matches_id'), 'pvp_matches', ['id'], unique=False)
    op.create_table('pvp_matchmaking_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('battle_type', sa.String(), nullable=True),
    sa.Column('rank', sa.String(), nullable=True),
    sa.Column('skill_xp', sa.Integer(), nullable=True),
    sa.Column('mmr', sa.Integer(), nullable=True),
    sa.Column('queue_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_pvp_matchmaking_queue_id'), 'pvp_matchmaking_queue', ['id'], unique=False)
    op.create_table('pvp_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('mmr', sa.Integer(), nullable=True),
    sa.Column('matches_played', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('draws', sa.Integer(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('highest_mmr', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_pvp_ratings_id'), 'pvp_ratings', ['id'], unique=False)
    op.create_table('reel_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reel_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['reel_id'], ['reels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reel_likes_id'), 'reel_likes', ['id'], unique=False)
    op.create_table('skill_activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('activity_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_activity_log_id'), 'skill_activity_log', ['id'], unique=False)
    op.create_index(op.f('ix_skill_activity_log_skill_id'), 'skill_activity_log', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skill_activity_log_user_id'), 'skill_activity_log', ['user_id'], unique=False)
    op.create_table('skill_leaderboards',
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_xp', sa.Integer(), nullable=True),
    sa.Column('rank_position', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('skill_id', 'user_id')
    )
    op.create_table('skill_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('media_url', sa.String(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_posts_id'), 'skill_posts', ['id'], unique=False)
    op.create_table('skill_proofs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('proof_type', sa.String(), nullable=False),
    sa.Column('proof_url', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_proofs_id'), 'skill_proofs', ['id'], unique=False)
    op.create_index(op.f('ix_skill_proofs_skill_id'), 'skill_proofs', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skill_proofs_user_id'), 'skill_proofs', ['user_id'], unique=False)
    op.create_table('skill_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('related_skill_id', sa.Integer(), nullable=True),
    sa.Column('relationship_strength', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['related_skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_relationships_id'), 'skill_relationships', ['id'], unique=False)
    op.create_index(op.f('ix_skill_relationships_related_skill_id'), 'skill_relationships', ['related_skill_id'], unique=False)
    op.create_index(op.f('ix_skill_relationships_skill_id'), 'skill_relationships', ['skill_id'], unique=False)
    op.create_table('skill_trending_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('skill_name', sa.String(), nullable=False),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('engagement_volume', sa.Integer(), nullable=True),
    sa.Column('growth_rate', sa.Float(), nullable=True),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_trending_data_id'), 'skill_trending_data', ['id'], unique=False)
    op.create_index(op.f('ix_skill_trending_data_skill_id'), 'skill_trending_data', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skill_trending_data_skill_name'), 'skill_trending_data', ['skill_name'], unique=True)
    op.create_table('user_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('skill_name', sa.String(), nullable=False),
    sa.Column('skill_level', sa.Integer(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('endorsement_count', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('skill_integrity_score', sa.Float(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_skills_id'), 'user_skills', ['id'], unique=False)
    op.create_index(op.f('ix_user_skills_skill_id'), 'user_skills', ['skill_id'], unique=False)
    op.create_table('post_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['skill_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_comments_id'), 'post_comments', ['id'], unique=False)
    op.create_table('post_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['skill_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_likes_id'), 'post_likes', ['id'], unique=False)
    op.create_table('pvp_match_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=True),
    sa.Column('player1_id', sa.Integer(), nullable=True),
    sa.Column('player2_id', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('battle_type', sa.String(), nullable=True),
    sa.Column('player1_score', sa.Integer(), nullable=True),
    sa.Column('player2_score', sa.Integer(), nullable=True),
    sa.Column('match_score', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['pvp_matches.id'], ),
    sa.ForeignKeyConstraint(['player1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pvp_match_history_id'), 'pvp_match_history', ['id'], unique=False)
    op.create_table('pvp_match_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('completion_time', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('xp_gained', sa.Integer(), nullable=True),
    sa.Column('mmr_change', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['pvp_matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pvp_match_results_id'), 'pvp_match_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pvp_match_results_id'), table_name='pvp_match_results')
    op.drop_table('pvp_match_results')
    op.drop_index(op.f('ix_pvp_match_history_id'), table_name='pvp_match_history')
    op.drop_table('pvp_match_history')
    op.drop_index(op.f('ix_post_likes_id'), table_name='post_likes')
    op.drop_table('post_likes')
    op.drop_index(op.f('ix_post_comments_id'), table_name='post_comments')
    op.drop_table('post_comments')
    op.drop_index(op.f('ix_user_skills_skill_id'), table_name='user_skills')
    op.drop_index(op.f('ix_user_skills_id'), table_name='user_skills')
    op.drop_table('user_skills')
    op.drop_index(op.f('ix_skill_trending_data_skill_name'), table_name='skill_trending_data')
    op.drop_index(op.f('ix_skill_trending_data_skill_id'), table_name='skill_trending_data')
    op.drop_index(op.f('ix_skill_trending_data_id'), table_name='skill_trending_data')
    op.drop_table('skill_trending_data')
    op.drop_index(op.f('ix_skill_relationships_skill_id'), table_name='skill_relationships')
    op.drop_index(op.f('ix_skill_relationships_related_skill_id'), table_name='skill_relationships')
    op.drop_index(op.f('ix_skill_relationships_id'), table_name='skill_relationships')
    op.drop_table('skill_relationships')
    op.drop_index(op.f('ix_skill_proofs_user_id'), table_name='skill_proofs')
    op.drop_index(op.f('ix_skill_proofs_skill_id'), table_name='skill_proofs')
    op.drop_index(op.f('ix_skill_proofs_id'), table_name='skill_proofs')
    op.drop_table('skill_proofs')
    op.drop_index(op.f('ix_skill_posts_id'), table_name='skill_posts')
    op.drop_table('skill_posts')
    op.drop_table('skill_leaderboards')
    op.drop_index(op.f('ix_skill_activity_log_user_id'), table_name='skill_activity_log')
    op.drop_index(op.f('ix_skill_activity_log_skill_id'), table_name='skill_activity_log')
    op.drop_index(op.f('ix_skill_activity_log_id'), table_name='skill_activity_log')
    op.drop_table('skill_activity_log')
    op.drop_index(op.f('ix_reel_likes_id'), table_name='reel_likes')
    op.drop_table('reel_likes')
    op.drop_index(op.f('ix_pvp_ratings_id'), table_name='pvp_ratings')
    op.drop_table('pvp_ratings')
    op.drop_index(op.f('ix_pvp_matchmaking_queue_id'), table_name='pvp_matchmaking_queue')
    op.drop_table('pvp_matchmaking_queue')
    op.drop_index(op.f('ix_pvp_matches_id'), table_name='pvp_matches')
    op.drop_table('pvp_matches')
    op.drop_index(op.f('ix_post_media_post_id'), table_name='post_media')
    op.drop_index(op.f('ix_post_media_id'), table_name='post_media')
    op.drop_table('post_media')
    op.drop_index(op.f('ix_messages_room_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_is_read'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_match_submissions_id'), table_name='match_submissions')
    op.drop_table('match_submissions')
    op.drop_index(op.f('ix_community_posts_id'), table_name='community_posts')
    op.drop_table('community_posts')
    op.drop_index(op.f('ix_community_members_id'), table_name='community_members')
    op.drop_table('community_members')
    op.drop_table('user_social_stats')
    op.drop_table('user_security_score')
    op.drop_index(op.f('ix_user_resumes_user_id'), table_name='user_resumes')
    op.drop_index(op.f('ix_user_resumes_id'), table_name='user_resumes')
    op.drop_table('user_resumes')
    op.drop_table('user_reputation')
    op.drop_table('user_rank')
    op.drop_index(op.f('ix_user_quest_status_id'), table_name='user_quest_status')
    op.drop_table('user_quest_status')
    op.drop_index(op.f('ix_user_projects_user_id'), table_name='user_projects')
    op.drop_index(op.f('ix_user_projects_id'), table_name='user_projects')
    op.drop_table('user_projects')
    op.drop_table('user_privacy_settings')
    op.drop_index(op.f('ix_user_presence_is_online'), table_name='user_presence')
    op.drop_table('user_presence')
    op.drop_table('user_notification_settings')
    op.drop_index(op.f('ix_user_media_id'), table_name='user_media')
    op.drop_table('user_media')
    op.drop_index(op.f('ix_user_interests_id'), table_name='user_interests')
    op.drop_table('user_interests')
    op.drop_index(op.f('ix_user_goals_user_id'), table_name='user_goals')
    op.drop_index(op.f('ix_user_goals_id'), table_name='user_goals')
    op.drop_table('user_goals')
    op.drop_index(op.f('ix_user_connections_user2_id'), table_name='user_connections')
    op.drop_index(op.f('ix_user_connections_user1_id'), table_name='user_connections')
    op.drop_index(op.f('ix_user_connections_id'), table_name='user_connections')
    op.drop_table('user_connections')
    op.drop_index(op.f('ix_user_activities_id'), table_name='user_activities')
    op.drop_table('user_activities')
    op.drop_index(op.f('ix_user_achievements_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_table('user_account_settings')
    op.drop_index(op.f('ix_tournament_rewards_id'), table_name='tournament_rewards')
    op.drop_table('tournament_rewards')
    op.drop_table('tournament_participants')
    op.drop_index(op.f('ix_tournament_matches_id'), table_name='tournament_matches')
    op.drop_table('tournament_matches')
    op.drop_index(op.f('ix_social_graph_edges_id'), table_name='social_graph_edges')
    op.drop_table('social_graph_edges')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_canonical_name'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_skill_endorsements_target_user_id'), table_name='skill_endorsements')
    op.drop_index(op.f('ix_skill_endorsements_skill_name'), table_name='skill_endorsements')
    op.drop_index(op.f('ix_skill_endorsements_id'), table_name='skill_endorsements')
    op.drop_index(op.f('ix_skill_endorsements_endorser_user_id'), table_name='skill_endorsements')
    op.drop_table('skill_endorsements')
    op.drop_index(op.f('ix_skill_badges_id'), table_name='skill_badges')
    op.drop_table('skill_badges')
    op.drop_index(op.f('ix_rivalries_id'), table_name='rivalries')
    op.drop_table('rivalries')
    op.drop_index(op.f('ix_reels_id'), table_name='reels')
    op.drop_table('reels')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_match_queue_id'), table_name='match_queue')
    op.drop_table('match_queue')
    op.drop_table('leaderboard')
    op.drop_index(op.f('ix_followers_id'), table_name='followers')
    op.drop_table('followers')
    op.drop_index(op.f('ix_feed_cache_id'), table_name='feed_cache')
    op.drop_table('feed_cache')
    op.drop_index(op.f('ix_external_accounts_id'), table_name='external_accounts')
    op.drop_table('external_accounts')
    op.drop_table('creator_monetization')
    op.drop_table('creator_metrics')
    op.drop_index(op.f('ix_connection_requests_sender_id'), table_name='connection_requests')
    op.drop_index(op.f('ix_connection_requests_receiver_id'), table_name='connection_requests')
    op.drop_index(op.f('ix_connection_requests_id'), table_name='connection_requests')
    op.drop_table('connection_requests')
    op.drop_index(op.f('ix_communities_slug'), table_name='communities')
    op.drop_index(op.f('ix_communities_name'), table_name='communities')
    op.drop_index(op.f('ix_communities_id'), table_name='communities')
    op.drop_table('communities')
    op.drop_index(op.f('ix_chat_rooms_id'), table_name='chat_rooms')
    op.drop_table('chat_rooms')
    op.drop_index(op.f('ix_battle_pass_tiers_id'), table_name='battle_pass_tiers')
    op.drop_table('battle_pass_tiers')
    op.drop_table('ai_profile_insights')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tournaments_id'), table_name='tournaments')
    op.drop_table('tournaments')
    op.drop_index(op.f('ix_skill_categories_id'), table_name='skill_categories')
    op.drop_table('skill_categories')
    op.drop_index(op.f('ix_pvp_challenges_id'), table_name='pvp_challenges')
    op.drop_table('pvp_challenges')
    op.drop_index(op.f('ix_platform_metrics_id'), table_name='platform_metrics')
    op.drop_index(op.f('ix_platform_metrics_date'), table_name='platform_metrics')
    op.drop_table('platform_metrics')
    op.drop_index(op.f('ix_daily_quests_id'), table_name='daily_quests')
    op.drop_table('daily_quests')
    op.drop_index(op.f('ix_battle_pass_seasons_id'), table_name='battle_pass_seasons')
    op.drop_table('battle_pass_seasons')
    op.drop_index(op.f('ix_achievements_id'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
